spring.application.name=backend
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/SafeTrack?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=17012431
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# SMTP settings for sending email (e.g., using Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pulithamarasinghe@gmail.com
spring.mail.password=ryco rwjo abdx mopp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=*

google.maps.api.key=AIzaSyCSBBiJ1FlfAgReJyDEgDrwiX0R0CLIGHM

stripe.api.key=sk_test_51R8p1zGayA7H0BqG2IeKsq0KOojVwllEZwheRXLLPxOcg1rfQRFAHi5URaC1ilRBrv2ZZoJSVulxoiK6my9fZoSZ00JJejENwc

stripe.webhook.secret=whsec_71a9f001cd07138fd4316e3325a849fd9b482bb0130c5313f3b40755ff3f58cc

# ========== STUDENT AVAILABILITY API ==========
student.availability.api.base-url=/api/availability


