import React, { useEffect, useState } from "react";
import axios from "axios";
import { SearchIcon } from "lucide-react";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export default function ExpectedStdMgt() {
  const [students, setStudents] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState("");
  const [sortConfig, setSortConfig] = useState({ key: "noPlate", direction: "asc" });
  const [filterDate, setFilterDate] = useState("");
  const [filterComing, setFilterComing] = useState("");
  const [filterNoPlate, setFilterNoPlate] = useState("");

  useEffect(() => {
    fetchExpectedStudents();
  }, []);

  const fetchExpectedStudents = async () => {
    try {
      const res = await axios.get("http://localhost:8080/api/availability/getAll");
      console.log("Fetched students:", res.data);
      setStudents(res.data);
    } catch (err) {
      console.error("Failed to fetch expected students", err);
    } finally {
      setLoading(false);
    }
  };

  const clearFilters = () => {
    setSearchTerm("");
    setFilterDate("");
    setFilterComing("");
    setFilterNoPlate("");
  };

  const filteredStudents = students.filter((student) => {
    const matchesSearch =
      student.studentName?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      student.email?.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesDate = !filterDate || student.date === filterDate;
    const matchesComing =
      !filterComing ||
      (filterComing === "Yes" && student.coming) ||
      (filterComing === "No" && !student.coming);
    const matchesNoPlate = !filterNoPlate || student.noPlate === filterNoPlate;

    return matchesSearch && matchesDate && matchesComing && matchesNoPlate;
  });

  const generateReport = () => {
    const doc = new jsPDF({ orientation: "landscape", unit: "mm" });

    doc.setFontSize(20);
    doc.setTextColor(40, 53, 147);
    doc.setFont("helvetica", "bold");
    doc.text("STUDENT TRANSPORT AVAILABILITY REPORT", doc.internal.pageSize.width / 2, 20, {
      align: "center",
    });

    doc.setFontSize(12);
    doc.setTextColor(81, 81, 81);
    doc.setFont("helvetica", "normal");
    doc.text("Generated by School Transport Management System", doc.internal.pageSize.width / 2, 27, {
      align: "center",
    });

    doc.setFontSize(10);
    doc.text(
      `Generated on: ${new Date().toLocaleString("en-US", {
        year: "numeric", month: "long", day: "numeric", hour: "2-digit", minute: "2-digit",
      })}`,
      15, 35
    );
    doc.text(`Total Records: ${filteredStudents.length}`, doc.internal.pageSize.width - 15, 35, {
      align: "right",
    });

    doc.setFont("helvetica", "bold");
    doc.text("Filters Applied:", 15, 45);
    doc.setFont("helvetica", "normal");

    let filterY = 50;
    if (filterDate) {
      doc.text(`Date: ${new Date(filterDate).toLocaleDateString()}`, 20, filterY);
      filterY += 5;
    }
    if (filterComing) {
      doc.text(`Availability: ${filterComing}`, 20, filterY);
      filterY += 5;
    }
    if (filterNoPlate) {
      doc.text(`Number Plate: ${filterNoPlate}`, 20, filterY);
      filterY += 5;
    }
    if (!filterDate && !filterComing && !filterNoPlate) {
      doc.text("No filters applied", 20, filterY);
    }

    const tableColumn = [
      { header: "Student Name", dataKey: "studentName" },
      { header: "Email", dataKey: "email" },
      { header: "Date", dataKey: "date" },
      { header: "Available", dataKey: "coming" },
      { header: "Attendance Type", dataKey: "attendanceType" },
      { header: "Reason", dataKey: "reason" },
      { header: "Number Plate", dataKey: "noPlate" },
    ];

    const tableData = filteredStudents.map((student) => ({
      studentName: student.studentName || "N/A",
      email: student.email || "N/A",
      date: student.date ? new Date(student.date).toLocaleDateString() : "N/A",
      coming: student.coming ? "Yes" : "No",
      attendanceType: student.attendanceType || "N/A",
      reason: student.reason || "N/A",
      noPlate: student.noPlate || "N/A",
    }));

    autoTable(doc, {
      startY: filterY + 10,
      columns: tableColumn,
      body: tableData,
      theme: "grid",
      headStyles: {
        fillColor: [40, 53, 147],
        textColor: 255,
        fontStyle: "bold",
        fontSize: 10,
      },
      bodyStyles: {
        textColor: [51, 51, 51],
        fontSize: 9,
      },
      alternateRowStyles: { fillColor: [240, 240, 240] },
      margin: { left: 10, right: 10 },
      styles: { cellPadding: 4, overflow: "linebreak", halign: "left" },
      columnStyles: {
        studentName: { cellWidth: 25 },
        email: { cellWidth: 35 },
        date: { cellWidth: 15 },
        coming: { cellWidth: 12, halign: "center" },
        attendanceType: { cellWidth: 20 },
        reason: { cellWidth: 30 },
        noPlate: { cellWidth: 20 },
      },
      didDrawPage: (data) => {
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(
          `Page ${data.pageCount}`,
          doc.internal.pageSize.width / 2,
          doc.internal.pageSize.height - 10,
          { align: "center" }
        );
      },
    });

    doc.save(`Student_Transport_Availability_${new Date().toISOString().slice(0, 10)}.pdf`);
  };

  const uniqueNoPlates = [...new Set(students.map((s) => s.noPlate).filter(Boolean))];

  return (
    <div className="container mx-auto p-4 space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-800">Expected Student Management</h1>
        <p className="text-gray-600">Track student availability and pickup expectations</p>
      </div>

      <div className="bg-white rounded-lg shadow p-4 border-b flex flex-col md:flex-row md:items-center md:justify-between space-y-3 md:space-y-0">
        <div className="flex flex-col md:flex-row md:items-center space-y-3 md:space-y-0 md:space-x-3 w-full md:w-auto">
          <div className="relative w-full md:w-64">
            <input
              type="text"
              placeholder="Search by name or email..."
              className="w-full pl-10 pr-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
            <SearchIcon className="absolute left-3 top-2.5 h-5 w-5 text-gray-400" />
          </div>

          <select
            value={filterNoPlate}
            onChange={(e) => setFilterNoPlate(e.target.value)}
            className="w-full md:w-40 pl-3 pr-8 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            <option value="">All Number Plates</option>
            {uniqueNoPlates.map((plate) => (
              <option key={plate} value={plate}>
                {plate}
              </option>
            ))}
          </select>

          <input
            type="date"
            value={filterDate}
            onChange={(e) => setFilterDate(e.target.value)}
            className="w-full md:w-40 pl-3 pr-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
          />

          <select
            value={filterComing}
            onChange={(e) => setFilterComing(e.target.value)}
            className="w-full md:w-40 pl-3 pr-8 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            <option value="">All Availability</option>
            <option value="Yes">Coming</option>
            <option value="No">Not Coming</option>
          </select>

          <button
            onClick={clearFilters}
            className="px-3 py-2 border rounded-lg text-sm bg-gray-200 hover:bg-gray-300"
          >
            Clear Filters
          </button>
        </div>

        <button
          onClick={generateReport}
          className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 flex items-center gap-2"
        >
          Generate Report
        </button>
      </div>

      <div className="bg-white rounded-lg shadow overflow-x-auto">
        {loading ? (
          <div className="p-8 text-center">Loading students...</div>
        ) : filteredStudents.length === 0 ? (
          <div className="p-8 text-center text-gray-500">No records found</div>
        ) : (
          <table className="w-full">
            <thead>
              <tr className="bg-gray-50">
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Name</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Email</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Date</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Coming</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Attendance Type</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Reason</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Number Plate</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-200">
              {filteredStudents.map((s) => (
                <tr key={s.id}>
                  <td className="px-6 py-4 text-sm text-gray-900">{s.studentName || "N/A"}</td>
                  <td className="px-6 py-4 text-sm text-gray-500">{s.email || "N/A"}</td>
                  <td className="px-6 py-4 text-sm text-gray-500">{s.date ? new Date(s.date).toLocaleDateString() : "N/A"}</td>
                  <td className="px-6 py-4 text-sm text-gray-500">{s.coming ? "Yes" : "No"}</td>
                  <td className="px-6 py-4 text-sm text-gray-500">{s.attendanceType || "N/A"}</td>
                  <td className="px-6 py-4 text-sm text-gray-500">{s.reason || "N/A"}</td>
                  <td className="px-6 py-4 text-sm text-gray-500">{s.noPlate || "N/A"}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}